#20220806 wangyide:application.ymlの作成
server:
  port: 8989 #指定端口
  servlet:
    context-path: /SystemKyujin  #制定项目名
    jsp:
      init-parameters:
        development: true   #开启jsp模板的开发模式
#配置jsp模板
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:orcl2?useUnicode=true&characterEncoding=utf8
    username: aidijava
    password: aidijava
#配置mybatis
mybatis:
  mapper-locations: classpath:com/example/mapper/*.xml
  type-aliases-package: com.example
#配置日志的使用
logging:
  level:
    root: info
    com.example: debug  #指定包日志
pagehelper:
  # 指定数据库
  helper-dialect: oracle
  # 默认是false。启用合理化时，如果pageNum<1会查询第一页，如果pageNum>pages（最大页数）会查询最后一页。禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
  reasonable: true
  # 是否支持接口参数来传递分页参数，默认false
  support-methods-arguments: true
  # 为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值， 可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值， 默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
  params: count=countSql
  row-bounds-with-count: true
