CREATE TABLE AIDIJAVA.ROLE_TABLE ( 
	R_ID						NUMBER(11)		NOT NULL,
	R_TYPE						NUMBER(1)		NOT NULL,
	R_NAME						VARCHAR2(20)	NOT NULL,
	KOUSHIN_SHA					VARCHAR2(10),
	KOUSHIN_HIDUKE				DATE,
	SAKUSEI_SHA					VARCHAR2(10),
	SAKUSEI_HIDUKE				DATE,
	DEL_FLAG					NUMBER(1)		DEFAULT 0  	NOT NULL,
	STATUS						NUMBER(3), 
	CHECK(R_TYPE = 1 OR R_TYPE = 2 OR
                                                                                         R_TYPE = 3 OR R_TYPE = 4) , 
	CHECK(DEL_FLAG = 0 OR DEL_FLAG = 1) , 
	PRIMARY KEY(R_ID) 
		USING INDEX TABLESPACE USERS LOGGING PCTFREE 10 INITRANS 2 MAXTRANS 255 
			STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED  
				BUFFER_POOL DEFAULT ) 
) 
TABLESPACE USERS LOGGING PCTFREE 10 INITRANS 1 MAXTRANS 255 
	STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED  
		BUFFER_POOL DEFAULT ) MONITORING 
/
