CREATE TABLE AIDIJAVA.USER_ROLE_TABLE ( 
	UR_ID						NUMBER(11)		NOT NULL,
	U_ID						NUMBER(11)		NOT NULL,
	R_ID						NUMBER(11)		NOT NULL,
	U_NAME						VARCHAR2(20),
	R_NAME						VARCHAR2(20),
	KOUSHIN_HIDUKE				DATE,
	SAKUSEI_SHA					VARCHAR2(10),
	SAKUSEI_HIDUKE				DATE,
	DEL_FLAG					NUMBER(1)		DEFAULT 0  	NOT NULL,
	STATUS						NUMBER(3), 
	CONSTRAINT FK_RID FOREIGN KEY(R_ID) REFERENCES AIDIJAVA.ROLE_TABLE (R_ID) , 
	CONSTRAINT FK_UID FOREIGN KEY(U_ID) REFERENCES AIDIJAVA.USER_TABLE (U_ID) , 
	CHECK(DEL_FLAG = 0 OR DEL_FLAG = 1) , 
	PRIMARY KEY(UR_ID) 
		USING INDEX TABLESPACE USERS LOGGING PCTFREE 10 INITRANS 2 MAXTRANS 255 
			STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED  
				BUFFER_POOL DEFAULT ) 
) 
TABLESPACE USERS LOGGING PCTFREE 10 INITRANS 1 MAXTRANS 255 
	STORAGE(INITIAL 64K NEXT 1M MINEXTENTS 1 MAXEXTENTS UNLIMITED  
		BUFFER_POOL DEFAULT ) MONITORING 
/
